# Configuation for robot odometry EKF

frequency: 50
sensor_timeout: 0.1
two_d_mode: true
transform_time_offset: 0.0
transform_timeout: 0.0
print_diagnostics: true
debug: false

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom
publish_tf: true



imu0: /handsfree/imu
imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              false,  false,  false,
              false,  false,  false]

imu0_differential: false
imu0_relative: false
