# Common Configuration (local_costmap) & (global_costmap)

obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.5, -0.25], [0.5, 0.25], [-0.5, 0.25], [-0.5, -0.25]]
inflation_radius: 0.05
resolution: 0.01

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}